/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FitmentRouteImport } from './routes/fitment'
import { Route as TyresRouteImport } from './routes/tyres'
import { Route as TyresIndexRouteImport } from './routes/tyres.index'
import { Route as TyresTyreIdRouteImport } from './routes/tyres.$tyreId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FitmentRoute = FitmentRouteImport.update({
  id: '/fitment',
  path: '/fitment',
  getParentRoute: () => rootRouteImport,
} as any)
const TyresRoute = TyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => rootRouteImport,
} as any)
const TyresIndexRoute = TyresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TyresRoute,
} as any)
const TyresTyreIdRoute = TyresTyreIdRouteImport.update({
  id: '/$tyreId',
  path: '/$tyreId',
  getParentRoute: () => TyresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fitment': typeof FitmentRoute
  '/tyres': typeof TyresRouteWithChildren
  '/tyres/$tyreId': typeof TyresTyreIdRoute
  '/tyres/': typeof TyresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fitment': typeof FitmentRoute
  '/tyres/$tyreId': typeof TyresTyreIdRoute
  '/tyres': typeof TyresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fitment': typeof FitmentRoute
  '/tyres': typeof TyresRouteWithChildren
  '/tyres/$tyreId': typeof TyresTyreIdRoute
  '/tyres/': typeof TyresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fitment' | '/tyres' | '/tyres/$tyreId' | '/tyres/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fitment' | '/tyres/$tyreId' | '/tyres'
  id: '__root__' | '/' | '/fitment' | '/tyres' | '/tyres/$tyreId' | '/tyres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FitmentRoute: typeof FitmentRoute
  TyresRoute: typeof TyresRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitment': {
      id: '/fitment'
      path: '/fitment'
      fullPath: '/fitment'
      preLoaderRoute: typeof FitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tyres': {
      id: '/tyres'
      path: '/tyres'
      fullPath: '/tyres'
      preLoaderRoute: typeof TyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tyres/': {
      id: '/tyres/'
      path: '/'
      fullPath: '/tyres/'
      preLoaderRoute: typeof TyresIndexRouteImport
      parentRoute: typeof TyresRoute
    }
    '/tyres/$tyreId': {
      id: '/tyres/$tyreId'
      path: '/$tyreId'
      fullPath: '/tyres/$tyreId'
      preLoaderRoute: typeof TyresTyreIdRouteImport
      parentRoute: typeof TyresRoute
    }
  }
}

interface TyresRouteChildren {
  TyresTyreIdRoute: typeof TyresTyreIdRoute
  TyresIndexRoute: typeof TyresIndexRoute
}

const TyresRouteChildren: TyresRouteChildren = {
  TyresTyreIdRoute: TyresTyreIdRoute,
  TyresIndexRoute: TyresIndexRoute,
}

const TyresRouteWithChildren = TyresRoute._addFileChildren(TyresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FitmentRoute: FitmentRoute,
  TyresRoute: TyresRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
